# Generated by Django 2.1.2 on 2018-10-25 10:43

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogID', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=128)),
                ('authorID', models.CharField(max_length=7)),
                ('isLive', models.BooleanField(default=False)),
                ('likes', models.IntegerField()),
                ('tags', models.CharField(max_length=200)),
                ('views', models.IntegerField()),
                ('lastUpdated', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('createdAt', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('content', models.TextField()),
                ('approvedBy', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentID', models.CharField(max_length=17)),
                ('isLive', models.BooleanField(default=False)),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('emailID', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('mobile', models.IntegerField()),
                ('totalBlogsWritten', models.IntegerField()),
                ('isBlocked', models.BooleanField(default=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isModerator', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.UserDetails'),
        ),
        migrations.AddField(
            model_name='comment',
            name='blogID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.Blog'),
        ),
    ]
