# Generated by Django 2.1.2 on 2018-10-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20181025_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emailID',
            field=models.EmailField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userID',
            field=models.IntegerField(null=True),
        ),
    ]
