# Generated by Django 2.1.2 on 2018-10-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20181025_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='totalBlogsWritten',
            field=models.IntegerField(default=0),
        ),
    ]
