# Generated by Django 2.1.2 on 2018-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20181026_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='j', max_length=7),
        ),
        migrations.AddField(
            model_name='comment',
            name='blogID',
            field=models.CharField(default='d', max_length=11),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userID',
            field=models.CharField(default='a', max_length=7),
        ),
    ]
