# Generated by Django 2.1.2 on 2018-10-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20181031_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userID',
            field=models.CharField(max_length=7),
        ),
    ]
