# Generated by Django 2.1.2 on 2018-11-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20181031_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='approvedBy',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
