# Generated by Django 2.1.2 on 2018-11-05 13:12

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20181102_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=50)),
                ('emailID', models.EmailField(max_length=50)),
                ('logInTime', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('logOutTime', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('isExpired', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AddField(
            model_name='blog',
            name='topic',
            field=models.CharField(default='technology', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emailID',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
