# Generated by Django 2.1.2 on 2018-11-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20181104_1453'),
        ('blogs', '0012_auto_20181105_1312'),
    ]

    operations = [
    ]
