# Generated by Django 2.1.2 on 2018-11-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_merge_20181105_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='Abhishek', max_length=50),
            preserve_default=False,
        ),
    ]
