# Generated by Django 2.1.2 on 2018-11-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_blog_name'),
        ('blogs', '0014_auto_20181106_0352'),
    ]

    operations = [
    ]
