# Generated by Django 2.1.3 on 2018-11-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_userdetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(default='images/profile_pic.png', upload_to='images/'),
        ),
    ]
