# Generated by Django 2.1.3 on 2018-11-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_auto_20181106_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='approvedBy',
            field=models.CharField(default='Anubhav', max_length=7),
            preserve_default=False,
        ),
    ]
