# Generated by Django 2.1.3 on 2018-11-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_auto_20181106_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='approvedBy',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
