# Generated by Django 2.1.3 on 2018-11-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_auto_20181106_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emailID',
            field=models.EmailField(max_length=50),
        ),
    ]
