# Generated by Django 2.1.3 on 2018-12-10 12:47

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_auto_20181110_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='logInTime',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='logOutTime',
            field=django_unixdatetimefield.fields.UnixDateTimeField(null=True),
        ),
    ]
