# Generated by Django 2.1.3 on 2018-12-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_auto_20181210_1817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
