# Generated by Django 2.1.2 on 2019-01-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_auto_20181226_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='approvedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
