# Generated by Django 2.1.2 on 2018-12-29 19:29

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='exit_poll_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_codes_used', models.IntegerField(default=0)),
                ('candidate_for_vp_1', models.IntegerField()),
                ('candidate_for_vp_2', models.IntegerField()),
                ('candidate_for_techboardGS_1', models.IntegerField()),
                ('candidate_for_techboardGS_2', models.IntegerField()),
                ('candidate_for_welfareboardGS_1', models.IntegerField()),
                ('candidate_for_welfareboardGS_2', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='individual_survey_exit_poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=50)),
                ('candidate_for_VP', models.CharField(max_length=50)),
                ('candidate_for_techboardGS', models.CharField(max_length=50)),
                ('candidate_for_welfareboardGS', models.CharField(max_length=50)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='individual_survey_pre_poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=50)),
                ('candidate_for_VP', models.CharField(max_length=50)),
                ('candidate_for_techboardGS', models.CharField(max_length=50)),
                ('candidate_for_welfareboardGS', models.CharField(max_length=50)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='pre_polls_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_codes_used', models.IntegerField(default=0)),
                ('candidate_for_vp_1', models.IntegerField()),
                ('candidate_for_vp_2', models.IntegerField()),
                ('candidate_for_techboardGS_1', models.IntegerField()),
                ('candidate_for_techboardGS_2', models.IntegerField()),
                ('candidate_for_welfareboardGS_1', models.IntegerField()),
                ('candidate_for_welfareboardGS_2', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('createdAt', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True)),
                ('authorID', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('is_Live', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
