# Generated by Django 2.1.2 on 2018-12-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='is_Live',
            new_name='isLive',
        ),
    ]
