# Generated by Django 2.1.5 on 2019-03-13 12:18

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_totalvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestingPost', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question_exit_poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('contestingPost', models.CharField(max_length=50)),
                ('totalVotes', models.IntegerField(default=0)),
                ('createdAt', django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True)),
                ('authorID', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('isLive', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='exit_poll_stats',
        ),
        migrations.DeleteModel(
            name='individual_survey_exit_poll',
        ),
        migrations.DeleteModel(
            name='individual_survey_pre_poll',
        ),
        migrations.DeleteModel(
            name='pre_polls_stats',
        ),
        migrations.AddField(
            model_name='candidate',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question_exit_poll'),
        ),
    ]
